### PR TITLE
Don't normalize commands

### LINKED ISSUE #30: If a folder named 'docker' is in the current directory, rustwide will try to execute it
With a docker directory:
```
(bash@joshua-ThinkPad-P51s) ~/.../rust/docs.rs ▶️ ls -ld docker/
drwxrwxr-x 2 joshua joshua 4096 Jun 28 21:49 docker/
(bash@joshua-ThinkPad-P51s) ~/.../rust/docs.rs ▶️ cargo run build crate regex 0.3.0
    Finished dev [unoptimized + debuginfo] target(s) in 0.23s
     Running `/home/joshua/.local/lib/cargo/target/debug/cratesfyi build crate regex 0.3.0`
2020/06/28 22:12:57 [DEBUG] cratesfyi::docbuilder: Loading cache
2020/06/28 22:12:57 [DEBUG] cratesfyi::docbuilder: Loading database cache
2020/06/28 22:12:57 [INFO] rustwide::cmd::sandbox: pulling image rustops/crates-build-env from Docker Hub
2020/06/28 22:12:57 [INFO] rustwide::cmd: running `Command { std: "/home/joshua/src/rust/docs.rs/docker" "pull" "rustops/crates-build-env", kill_on_drop: false }`
2020/06/28 22:12:57 [ERROR] rustwide::cmd: error running command: Permission denied (os error 13)
thread 'main' panicked at 'failed to initialize rustwide: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/bin/cratesfyi.rs:323:21
```

Without a docker directory:
```
(bash@joshua-ThinkPad-P51s) ~/.../rust/docs.rs ▶️ ls -ld docker
ls: cannot access 'docker': No such file or directory
(bash@joshua-ThinkPad-P51s) ~/.../rust/docs.rs ▶️ cargo run build crate regex 0.3.0
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `/home/joshua/.local/lib/cargo/target/debug/cratesfyi build crate regex 0.3.0`
2020/06/28 22:13:32 [DEBUG] cratesfyi::docbuilder: Loading cache
2020/06/28 22:13:32 [DEBUG] cratesfyi::docbuilder: Loading database cache
2020/06/28 22:13:32 [INFO] rustwide::cmd::sandbox: pulling image rustops/crates-build-env from Docker Hub
2020/06/28 22:13:32 [INFO] rustwide::cmd: running `Command { std: "docker" "pull" "rustops/crates-build-env", kill_on_drop: false }`
2020/06/28 22:13:32 [INFO] rustwide::cmd: [stdout] Using default tag: latest
2020/06/28 22:13:33 [INFO] rustwide::cmd: [stdout] latest: Pulling from rustops/crates-build-env
2020/06/28 22:13:33 [INFO] rustwide::cmd: [stdout] Digest: sha256:819119df93c0f5eca3f29186f14981ef29945a311854d7222af07488600a2584
2020/06/28 22:13:33 [INFO] rustwide::cmd: [stdout] Status: Image is up to date for rustops/crates-build-env:latest
2020/06/28 22:13:33 [INFO] rustwide::cmd: [stdout] docker.io/rustops/crates-build-env:latest
```

### PR DESCRIPTION
**Pull request by jyn514**
Since commands are looked up in PATH, their `Path` is unreliable and
cannot be treated as a normal directory.

Closes https://github.com/rust-lang/rustwide/issues/30

r? @pietroalbini

### CODE REVIEW

File: src/cmd/mod.rs [hunk 1]
```diff
@@ -381,7 +381,14 @@ impl<'w, 'pl> Command<'w, 'pl> {
...
                 Binary::__NonExaustive => panic!("do not create __NonExaustive variants manually"),
             };
-            let mut cmd = AsyncCommand::new(crate::utils::normalize_path(&binary));
+            // This is the relative path to a command,
+            // so we need to normalize it or it won't be found if we change directories
+            // NOTE: if components.count() == 1, then this is a command that will be looked up in $PATH,
+            // so we shouldn't normalize it.
+            if binary.is_relative() && binary.components().count() > 1 {
+                binary = crate::utils::normalize_path(&binary);
+            }
```
Comment (emilyalbini) [inline src/cmd/mod.rs]: Hmm, this is not the logic that we should use here. `normalize_path` should always be called for binaries managed by rustwide, and never be called for global binaries.

File: tests/buildtest/inside_docker.rs [hunk 2]
```diff
@@ -12,7 +12,15 @@ static CONTAINER_PREFIX: &str = "/outside";
...
 fn test_hello_world() {
+    // regression test for https://github.com/rust-lang/rustwide/issues/30
+    let already_present = Path::new("docker").exists();
+    if !already_present {
+        std::fs::create_dir("docker").unwrap();
+    }
     execute("buildtest::test_hello_world").unwrap();
+    if !already_present {
+        std::fs::remove_dir("docker").unwrap();
+    }
```
Comment (emilyalbini) [inline tests/buildtest/inside_docker.rs]: This will leave a stray `docker` directory if `execute()` fails. This test is also `#[cfg(unix)]`, so we wouldn't execute it on Windows while this is a bug that could happen there.

I'd create a new standalone test (`test/issue_30.rs`) that creates a temporary directory, `std::env::set_current_dir`s into it, creates a `true` directory and tries to call the global `true` binary. This needs to be in a standalone test to avoid the `std::env::set_current_dir` affecting other tests.

**Review by emilyalbini — CHANGES_REQUESTED** [review]
This also needs a line in the changelog.

File: tests/buildtest/inside_docker.rs (hunk 2 above)
Comment (jyn514) [reply tests/buildtest/inside_docker.rs]: Added a new standalone test.

File: CHANGELOG.md [hunk 3]
```diff
@@ -9,6 +9,11 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 
 - New method `Toolchain::remove_component`
 
+### Fixed
+
+- When passed a global command with the same name as a file in the current directory,
+Rustwide will now execute the global command instead of the file.
```
Comment (emilyalbini) [inline CHANGELOG.md]:
```suggestion
  Rustwide will now execute the global command instead of the file.
```

File: tests/integration/build_dir.rs [hunk 4]
```diff
@@ -0,0 +1,14 @@
+use failure::Error;
```
Comment (emilyalbini) [inline tests/integration/build_dir.rs]: Hm? This file is not included anywhere, and `purge_on_drop` is not implemented.

File: tests/issue_30.rs [hunk 5]
```diff
@@ -0,0 +1,24 @@
...
+    let env = env_logger::Builder::new()
+        .filter_module("rustwide", log::LevelFilter::Info)
+        .default_format_timestamp(false)
+        .is_test(true)
+        .build();
+    rustwide::logging::init_with(env);
+	let tmpdir = tempfile::tempdir()?;
+	std::env::set_current_dir(&tmpdir)?;
+	fs::write("true", b"foobar")?;
+	let workspace = WorkspaceBuilder::new(tempfile::tempdir()?.path(), USER_AGENT).fast_init(true).init()?;
```
Comment (emilyalbini) [inline tests/issue_30.rs]: Let's not create a brand new workspace every time this test is called, otherwise we need to compile the tools every time. Add `mod utils;` and call `crate::utils::init_workspace();` to get the shared test workspace.

File: tests/issue_30.rs [hunk 6]
```diff
@@ -0,0 +1,24 @@
...
+#[test]
+fn run_binary_with_same_name_as_file() -> Result<(), Error> {
+	use std::fs;
+
+    let env = env_logger::Builder::new()
+        .filter_module("rustwide", log::LevelFilter::Info)
+        .default_format_timestamp(false)
+        .is_test(true)
+        .build();
+    rustwide::logging::init_with(env);
```
Comment (emilyalbini) [inline tests/issue_30.rs]: This should be taken care of when you call `init_workspace()`.

**Review by emilyalbini — CHANGES_REQUESTED** [review]
Also you need to run `rustfmt`.

File: tests/integration/build_dir.rs (hunk 4 above)
Comment (jyn514) [reply tests/integration/build_dir.rs]: Oops, this slipped in from another branch. I removed it.

**Review by emilyalbini — APPROVED** [review]

**Comment by emilyalbini** [comment]
Released rustwide 0.9.0 with this change.
